# Generated by Django 5.2.17 on 2026-09-22 20:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContentBlob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("size", models.PositiveBigIntegerField()),
                ("storage_key", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("scope", models.CharField(max_length=200)),
                ("field", models.CharField(max_length=100)),
                ("kind", models.CharField(max_length=100)),
                ("revision", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="DraftRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("number", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("model_revision", models.CharField(blank=True, max_length=100)),
                ("prompt_revision", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ExtractedUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("extractor_revision", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=200)),
                ("locator", models.JSONField()),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="AuditRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("action", models.CharField(max_length=100)),
                ("object_id", models.UUIDField()),
                ("details", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BudgetAccount",
            fields=[
                ("key", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("limit", models.DecimalField(decimal_places=6, max_digits=12)),
                ("committed", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("limit__gte", 0), ("committed__gte", 0)),
                        name="budget_nonnegative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DecisionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("revision", models.PositiveIntegerField()),
                ("value", models.JSONField()),
                ("rationale", models.TextField()),
                ("evidence", models.JSONField(default=list)),
                ("resolver_revision", models.CharField(max_length=100)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.decision"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DraftExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("text", models.TextField()),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.draftrevision"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DraftSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.collection"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="draftrevision",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="proposal_app.draftsession"
            ),
        ),
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("suite_revision", models.CharField(max_length=100)),
                ("settings", models.JSONField(default=dict)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.collection"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EvaluationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("case", models.CharField(max_length=200)),
                ("result", models.JSONField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.evaluationrun"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvidencePacket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("payload", models.JSONField(default=list)),
                ("policy_revision", models.CharField(max_length=100)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.draftsession"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="draftrevision",
            name="packet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="proposal_app.evidencepacket"
            ),
        ),
        migrations.CreateModel(
            name="Identity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("issuer", models.CharField(max_length=300)),
                ("subject", models.CharField(max_length=300)),
                ("allowed", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("key", models.CharField(max_length=200)),
                ("kind", models.CharField(default="fixture", max_length=100)),
                ("state", models.CharField(default="queued", max_length=30)),
                ("payload", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("lease_token", models.UUIDField(null=True)),
                ("lease_until", models.DateTimeField(null=True)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("stop_reason", models.CharField(blank=True, max_length=100)),
                ("budget", models.DecimalField(decimal_places=6, max_digits=12)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.collection"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("number", models.PositiveIntegerField()),
                ("token", models.UUIDField(unique=True)),
                ("state", models.CharField(default="claimed", max_length=30)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.job"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("value", models.JSONField()),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.job"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LegacyImport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("sha256", models.CharField(max_length=64)),
                ("records", models.JSONField()),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.collection"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Outbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("delivered_at", models.DateTimeField(null=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.job"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("identifier", models.CharField(max_length=200)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.collection"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("revision", models.PositiveIntegerField()),
                ("state", models.CharField(default="staged", max_length=20)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.proposal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("eligible", models.BooleanField(default=False)),
                (
                    "blob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.contentblob"
                    ),
                ),
                (
                    "decision_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.decisionevent"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.extractedunit"
                    ),
                ),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proposal_app.publicationgeneration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("connector", models.CharField(max_length=80)),
                ("tenant", models.CharField(max_length=200)),
                ("site", models.CharField(max_length=200)),
                ("drive", models.CharField(max_length=200)),
                ("item", models.CharField(max_length=500)),
                ("display_path", models.TextField()),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.collection"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("observation_key", models.CharField(max_length=200)),
                ("upstream_version", models.CharField(max_length=200, null=True)),
                ("etag", models.CharField(max_length=300, null=True)),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "blob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.contentblob"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.sourceitem"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="extractedunit",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="proposal_app.sourceversion"
            ),
        ),
        migrations.CreateModel(
            name="UsageReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("reserved", models.DecimalField(decimal_places=6, max_digits=12)),
                ("charged", models.DecimalField(decimal_places=6, max_digits=12)),
                ("actual", models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ("state", models.CharField(default="reserved", max_length=30)),
                ("usage", models.JSONField(default=dict)),
                ("accounts", models.ManyToManyField(to="proposal_app.budgetaccount")),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.attempt"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VersionFamily",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("key", models.CharField(max_length=200)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.proposal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProposalMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.sourceitem"
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.versionfamily"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="decision",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="proposal_app.versionfamily"
            ),
        ),
        migrations.CreateModel(
            name="CollectionAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.collection"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("collection", "user"), name="collection_user")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="decisionevent",
            constraint=models.UniqueConstraint(
                fields=("decision", "revision"), name="decision_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationrecord",
            constraint=models.UniqueConstraint(fields=("run", "case"), name="evaluation_case"),
        ),
        migrations.AddConstraint(
            model_name="draftrevision",
            constraint=models.UniqueConstraint(fields=("session", "number"), name="draft_revision"),
        ),
        migrations.AddConstraint(
            model_name="identity",
            constraint=models.UniqueConstraint(
                fields=("issuer", "subject"), name="identity_subject"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["state", "available_at"], name="proposal_ap_state_657270_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=("collection", "key"), name="job_idempotency"
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.CheckConstraint(
                condition=models.Q(("budget__gte", 0)), name="job_budget_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.UniqueConstraint(fields=("job", "number"), name="job_attempt"),
        ),
        migrations.AddConstraint(
            model_name="legacyimport",
            constraint=models.UniqueConstraint(
                fields=("collection", "sha256"), name="legacy_import_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.UniqueConstraint(
                fields=("collection", "identifier"), name="proposal_identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationgeneration",
            constraint=models.UniqueConstraint(
                fields=("proposal", "revision"), name="publication_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationgeneration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("proposal",),
                name="one_active_generation",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceitem",
            constraint=models.UniqueConstraint(
                fields=("connector", "tenant", "site", "drive", "item"), name="source_identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceversion",
            constraint=models.UniqueConstraint(
                fields=("source", "observation_key"), name="source_observation"
            ),
        ),
        migrations.AddConstraint(
            model_name="extractedunit",
            constraint=models.UniqueConstraint(
                fields=("version", "extractor_revision", "key"), name="version_locator"
            ),
        ),
        migrations.AddConstraint(
            model_name="usagereservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reserved__gte", 0),
                    ("charged__gte", 0),
                    models.Q(("actual__isnull", True), ("actual__gte", 0), _connector="OR"),
                ),
                name="usage_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="versionfamily",
            constraint=models.UniqueConstraint(fields=("proposal", "key"), name="family_identity"),
        ),
        migrations.AddConstraint(
            model_name="proposalmembership",
            constraint=models.UniqueConstraint(
                fields=("source", "family"), name="source_membership"
            ),
        ),
        migrations.AddConstraint(
            model_name="decision",
            constraint=models.UniqueConstraint(
                fields=("family", "scope", "field", "kind"), name="decision_identity"
            ),
        ),
    ]
