# Generated by Django 5.2.17 on 2026-09-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposal_app", "0002_provenance_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="resume_state",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
