# Generated by Django 5.2.17 on 2026-09-23 02:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposal_app", "0005_local_product_slice"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("connector", models.CharField(max_length=80)),
                ("tenant", models.CharField(max_length=200)),
                ("site", models.CharField(max_length=200)),
                ("drive", models.CharField(max_length=200)),
                ("root_item", models.CharField(max_length=500)),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.collection"
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.proposal"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceSyncRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("state", models.CharField(default="running", max_length=30)),
                ("cursor", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("counts", models.JSONField(default=dict)),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.sourcescope"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourcePresence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("display_path", models.TextField()),
                ("retired_at", models.DateTimeField(null=True)),
                ("disposition", models.CharField(max_length=40)),
                ("reason", models.CharField(blank=True, max_length=200)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.sourceitem"
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.sourcescope"
                    ),
                ),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.sourcesyncrun"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceCaptureIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("source_item", models.CharField(max_length=500)),
                ("code", models.CharField(max_length=100)),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.sourcesyncrun"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="sourcescope",
            constraint=models.UniqueConstraint(
                fields=(
                    "collection",
                    "connector",
                    "tenant",
                    "site",
                    "drive",
                    "root_item",
                    "proposal",
                ),
                name="source_scope_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcesyncrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "running")),
                fields=("scope",),
                name="one_running_source_sync",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcepresence",
            constraint=models.UniqueConstraint(
                fields=("scope", "source"), name="scope_source_presence"
            ),
        ),
    ]
