# Generated by Django 5.2.17 on 2026-09-23 05:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposal_app", "0007_sourcepathevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedunit",
            name="context",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="extractedunit",
            name="kind",
            field=models.CharField(default="paragraph", max_length=40),
        ),
        migrations.AddField(
            model_name="extractedunit",
            name="warnings",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="sourceversion",
            name="observed_path",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ExtractionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("number", models.PositiveIntegerField()),
                ("fingerprint", models.CharField(max_length=64)),
                ("extractor_revision", models.CharField(max_length=100)),
                ("parser", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=30)),
                ("reason", models.CharField(blank=True, max_length=100)),
                ("recovery_action", models.CharField(blank=True, max_length=300)),
                ("warnings", models.JSONField(default=list)),
                ("active", models.BooleanField(default=False)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.sourceversion"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="extractedunit",
            name="extraction_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="proposal_app.extractionrun",
            ),
        ),
        migrations.CreateModel(
            name="FigureAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("key", models.CharField(max_length=200)),
                ("locator", models.JSONField()),
                ("mime_type", models.CharField(max_length=50)),
                ("caption", models.TextField(blank=True)),
                (
                    "blob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.contentblob"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.extractionrun"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisualInspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("locator", models.JSONField()),
                ("kind", models.CharField(max_length=20)),
                ("state", models.CharField(default="requested", max_length=30)),
                ("interpretation", models.TextField(blank=True)),
                ("source_check", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "figure",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proposal_app.figureasset",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.extractionrun"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="extractionrun",
            constraint=models.UniqueConstraint(
                fields=("version", "number"), name="extraction_run_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="extractionrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("version",),
                name="one_active_extraction",
            ),
        ),
        migrations.AddConstraint(
            model_name="figureasset",
            constraint=models.UniqueConstraint(fields=("run", "key"), name="run_figure_key"),
        ),
        migrations.AddConstraint(
            model_name="visualinspection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("figure__isnull", False)),
                fields=("run", "figure", "kind"),
                name="one_visual_request_per_figure",
            ),
        ),
    ]
