# Generated by Django 5.2.17 on 2026-09-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposal_app", "0008_extractedunit_context_extractedunit_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedunit",
            name="ordinal",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
