# Generated by Django 5.2.17 on 2026-09-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposal_app", "0009_extractedunit_ordinal"),
    ]

    operations = [
        migrations.AddField(
            model_name="visualinspection",
            name="adapter_revision",
            field=models.CharField(default="manual-v1", max_length=100),
        ),
    ]
