# Generated by Django 5.2.17 on 2026-09-24 17:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def mark_existing_answers(apps, schema_editor):
    Decision = apps.get_model("proposal_app", "Decision")
    Decision.objects.filter(decisionevent__isnull=False).update(status="resolved")


class Migration(migrations.Migration):

    dependencies = [
        ("proposal_app", "0010_visualinspection_adapter_revision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="affected_units",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="decision",
            name="critical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="decision",
            name="material_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="decision",
            name="recommendation",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="decision",
            name="recommendation_evidence",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="decision",
            name="recommendation_rationale",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="decision",
            name="status",
            field=models.CharField(default="unresolved", max_length=30),
        ),
        migrations.AddField(
            model_name="decisionevent",
            name="action",
            field=models.CharField(default="edit", max_length=30),
        ),
        migrations.AlterField(
            model_name="decisionevent",
            name="actor",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ClassificationFact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("dimension", models.CharField(max_length=40)),
                ("value", models.JSONField(null=True)),
                ("rationale", models.TextField()),
                ("evidence", models.JSONField(default=list)),
                ("resolver_revision", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=20)),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.versionfamily"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proposal_app.extractedunit",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.sourceversion"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("unit__isnull", False)),
                        fields=("family", "version", "unit", "dimension", "fingerprint"),
                        name="classification_unit_fingerprint",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("unit__isnull", True)),
                        fields=("family", "version", "dimension", "fingerprint"),
                        name="classification_version_fingerprint",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CurationPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("state", models.CharField(default="current", max_length=20)),
                ("eligible_units", models.JSONField(default=list)),
                ("excluded_units", models.JSONField(default=list)),
                ("derived_summaries", models.JSONField(default=list)),
                ("metadata_only", models.BooleanField(default=False)),
                ("decision_revisions", models.JSONField(default=dict)),
                ("warnings", models.JSONField(default=list)),
                (
                    "extraction_run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proposal_app.extractionrun",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.versionfamily"
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.sourceversion"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("family", "version", "fingerprint"), name="curation_plan_identity"
                    )
                ],
            },
        ),
        migrations.RunPython(mark_existing_answers, migrations.RunPython.noop),
    ]
