# Generated by Django 5.2.17 on 2026-09-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposal_app", "0011_decision_affected_units_decision_critical_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curationplan",
            name="voice_units",
            field=models.JSONField(default=list),
        ),
    ]
