# Generated by Django 5.2.17 on 2026-09-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposal_app", "0018_curated_evidence_pin_guard"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationartifact",
            name="index_state",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="publicationartifact",
            name="kind",
            field=models.CharField(default="excerpt", max_length=20),
        ),
        migrations.AddField(
            model_name="publicationartifact",
            name="locator",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="publicationartifact",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="publicationartifact",
            name="object_key",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="publicationartifact",
            name="source_unit_ids",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="publicationgeneration",
            name="backend",
            field=models.CharField(default="local", max_length=20),
        ),
        migrations.AddField(
            model_name="publicationgeneration",
            name="expected_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="publicationgeneration",
            name="failure",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="publicationgeneration",
            name="fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="publicationgeneration",
            name="ingestion_job_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="publicationgeneration",
            name="verified_at",
            field=models.DateTimeField(null=True),
        ),
    ]
