# Generated by Django 5.2.17 on 2026-09-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposal_app", "0019_publicationartifact_index_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationgeneration",
            name="deletion_job_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="publicationgeneration",
            name="deletion_state",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
