# Generated by Django 5.2.17 on 2026-09-28 14:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposal_app", "0023_publicationgeneration_indexing_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftrevision",
            name="checks",
            field=models.JSONField(default=list, db_default=[]),
        ),
        migrations.AddField(
            model_name="draftrevision",
            name="reuse_state",
            field=models.CharField(
                default="needs_review", db_default="needs_review", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="evidencepacket",
            name="model_request",
            field=models.JSONField(default=dict, db_default={}),
        ),
        migrations.CreateModel(
            name="DraftGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("expected_revision", models.PositiveIntegerField()),
                ("state", models.CharField(default="queued", max_length=30)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("reason", models.CharField(blank=True, max_length=100)),
                (
                    "packet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proposal_app.evidencepacket",
                    ),
                ),
                (
                    "result_revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proposal_app.draftrevision",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.draftsession"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EvidenceExclusion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.draftsession"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.sourceitem"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "source"), name="session_source_exclusion"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VoicePin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.curationplan"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.draftsession"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="proposal_app.extractedunit"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("session", "unit"), name="session_voice_pin")
                ],
            },
        ),
    ]
