# Generated by Django 5.2.17 on 2026-09-28 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposal_app", "0025_writing_reference_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftgeneration",
            name="provider_job",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="proposal_app.job"
            ),
        ),
    ]
